In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:98% !important;}
div.cell.code_cell.rendered{width:98%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:22pt;}
.inner_cell{font-size:22pt;}
div.text_cell_render pre code {font-size:22pt; line-height:30px;}
div.output {font-size:20pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:22pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:20pt;padding:5px;}
table.dataframe{font-size:22px;}
</style>
"""))

In [41]:
import pandas as pd  # 파일입력(read_excel), 교차표(crosstab), 원핫인코딩(get_dummies)
import numpy as np
from sklearn.model_selection import train_test_split #훈련셋과 시험셋 분리함수
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from tensorflow.keras.utils import to_categorical # 원핫인코딩
from tensorflow.keras.models import Sequential, save_model, load_model
from tensorflow.keras.layers import Dense, Input, Dropout # dropout은 과적합을 줄이기 위한 방법
import matplotlib.pyplot as plt #시각화
from sklearn.metrics import confusion_matrix #혼동행렬

# 이진분류(로지스틱 회귀분석)
- 1. 데이터셋 생성 & 전처리
    * 엑셀 -> 데이터프레임 -> ?처리 ..(결측치로 전환하여 결측치처리) -> X, y 분리
       -> X변수의 scale조정 -> train_test_split()을 이용하여 학습셋과 테스트셋을 분리
- 2. 모델 생성(입력13, 타겟1) - 과적합을 고려 & 학습과정 설정 & 학습
- 3. 모델 평가(그래프, 평가, 혼동행렬=교차표)
- 4. 모델 사용

In [5]:
df=pd.read_excel('data/heart-disease.xlsx',sheet_name='processed.cleveland')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   age           303 non-null    int64
 1   sex           303 non-null    int64
 2   cp            303 non-null    int64
 3   treshtbps     303 non-null    int64
 4   chol          303 non-null    object
 5   fbs           303 non-null    int64
 6   restecg       303 non-null    int64
 7   thalach       303 non-null    int64
 8   exang         303 non-null    int64
 9   oldpeak       303 non-null    float64
 10  slope         303 non-null    int64
 11  ca            303 non-null    object
 12  hsl           303 non-null    object
 13  heartDisease  303 non-null    int64
dtypes: float64(1), int64(10), object(3)
memory usage: 33.3+ KB

In [9]:
df.isnull().sum()

age             0
sex             0
cp              0
treshtbps       0
chol            0
fbs             0
restecg         0
thalach         0
exang           0
oldpeak         0
slope           0
ca              0
hsl             0
heartDisease    0
dtype: int64

In [ ]:
# 결측치 없는것 확인 but type중 object가 있음

In [10]:
df.isin(['?']).sum()

age             0
sex             0
cp              0
treshtbps       0
chol            1
fbs             0
restecg         0
thalach         0
exang           0
oldpeak         0
slope           0
ca              4
hsl             2
heartDisease    0
dtype: int64

In [12]:
df[(df['chol']=='?')|(df['ca']=='?')|(df['hsl']=='?')]

,age,sex,cp,treshtbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,hsl,heartDisease
2,67,1,4,120,?,0,2,129,1,2.6,2,2,7,1
87,53,0,3,128,216,0,2,115,0,0.0,1,0,?,0
166,52,1,3,138,223,0,0,169,0,0.0,1,?,3,0
192,43,1,4,132,247,1,2,143,1,0.1,2,?,7,1
266,52,1,4,128,204,1,0,156,1,1.0,2,0,?,1
287,58,1,2,125,220,0,0,144,0,0.4,2,?,7,0
302,38,1,3,138,175,0,0,173,0,0.0,1,?,3,0

In [16]:
# ?를 결측치로 대체 => 결측치 삭제
df=df.replace('?',np.nan)
df[(df['chol']=='?')|(df['ca']=='?')|(df['hsl']=='?')]

Empty DataFrame
Columns: [age, sex, cp, treshtbps, chol, fbs, restecg, thalach, exang, oldpeak, slope, ca, hsl, heartDisease]
Index: []

In [20]:
df[(df['chol'].isna())|(df['ca'].isna())|(df['hsl'].isna())]
df[df.isna().any(axis=1)]

,age,sex,cp,treshtbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,hsl,heartDisease
2,67,1,4,120,NaN,0,2,129,1,2.6,2,2.0,7.0,1
87,53,0,3,128,216.0,0,2,115,0,0.0,1,0.0,NaN,0
166,52,1,3,138,223.0,0,0,169,0,0.0,1,NaN,3.0,0
192,43,1,4,132,247.0,1,2,143,1,0.1,2,NaN,7.0,1
266,52,1,4,128,204.0,1,0,156,1,1.0,2,0.0,NaN,1
287,58,1,2,125,220.0,0,0,144,0,0.4,2,NaN,7.0,0
302,38,1,3,138,175.0,0,0,173,0,0.0,1,NaN,3.0,0

In [22]:
# 결측치 처리 : 삭제(dropna) cf.fillna() apply()
df=df.dropna(how='any') #결측치가 한 열이라도 있으면 삭제

In [27]:
df.shape

(296, 14)

In [31]:
#타겟변수 확인
df['heartDisease'].value_counts()/df.shape[0]

0    0.540541
1    0.459459
Name: heartDisease, dtype: float64

In [32]:
df['heartDisease'].value_counts(normalize=True)

0    0.540541
1    0.459459
Name: heartDisease, dtype: float64

In [36]:
# X,y분리 
X=df.iloc[:,:-1].values
y=df.iloc[:,-1:].values
X.shape, y.shape

((296, 13), (296, 1))

In [39]:
# X변수의 scale 조정
scaler= MinMaxScaler()
scaled_X=scaler.fit_transform(X)
print('원데이터:',X[0])
print('스케일 조정 데이터 :\n', scaled_X[0])

원데이터: [ 63.    1.    1.  145.  233.    1.    2.  150.    0.    2.3   3.    0.
   6. ]
스케일 조정 데이터 :
 [0.70833333 1.         0.         0.48113208 0.24429224 1.
 1.         0.60305344 0.         0.37096774 1.         0.
 0.75      ]

In [45]:
# scaled_X와 y를 학습데이터셋: 테스트셋 = 8:2
X_train, X_test, y_train, y_test=train_test_split(scaled_X, 
                                 y,
                                 #train_size=0.8
                                 test_size=0.2,
                                 random_state=7,
                                 stratify=y #층화추출
                                 )

In [46]:
#심장병 음성/양성 비율(y, y_train, y_test)   = > y의 train과 test 비율이 다름
print(pd.DataFrame(y).value_counts(normalize=True))
print(pd.DataFrame(y_train).value_counts(normalize=True))
print(pd.DataFrame(y_test).value_counts(normalize=True))

0    0.540541
1    0.459459
dtype: float64
0    0.542373
1    0.457627
dtype: float64
0    0.533333
1    0.466667
dtype: float64